{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/RioMDKPOC/Actions/RioFormsMDK/Service/UploadOffline.action",
    "OnFailure": "/RioMDKPOC/Actions/RioFormsMDK/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}