{
  "_Type": "Action.Type.OfflineOData.Upload",
  "_Name": "AutoSync_AfterCS",
  "Service": "/RioMDKPOC/Services/RioFormsMDK.service",
  "OnSuccess": "/RioMDKPOC/Actions/RioFormsMDK/Service/DownloadAfterUpload.action"
}
